apiVersion: v1
kind: Secret
metadata:
  name: movieflix
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnJlY29tbWVuZGF0aW9uX2ZpbG1zX29jdF8yM19NTE9QU0ByZWNvLWZpbG1zLWRiLmNrMnV1dmo4dGc1Yi5ldS13ZXN0LTMucmRzLmFtYXpvbmF3cy5jb206NTQzMi9wb3N0Z3Jlcw==
  USER: "cG9zdGdyZXM="
  DBNAME: "cG9zdGdyZXM="
  PASSWORD: "cmVjb21tZW5kYXRpb25fZmlsbXNfb2N0XzIzX01MT1BT"
  HOST: "cmVjby1maWxtcy1kYi5jazJ1dXZqOHRnNWIuZXUtd2VzdC0zLnJkcy5hbWF6b25hd3MuY29t"
  PORT: "NTQzMg=="
  SECRET_KEY: "c2VjcmV0"
  ALGORITHM: "SFMyNTY="
  ACCESS_TOKEN_EXPIRATION: MzA=
  MLFLOW_SERVER: aHR0cDovLzEzLjM5LjgwLjEyMjo1MDAwLw==
